apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kafka-standalone.fullname" . }}
  labels:
    {{- include "kafka-standalone.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kafka-standalone.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kafka-standalone.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
       - {{- toJson .Values.kafkaLogVolume | indent 1 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: kafka-client
              containerPort: 9092
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: kafka-client
            initialDelaySeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            periodSeconds: 5
            successThreshold: 1
          readinessProbe:
            tcpSocket:
              port: kafka-client
            initialDelaySeconds: 5
            timeoutSeconds: 5
            failureThreshold: 6
            periodSeconds: 5
            successThreshold: 1
          volumeMounts:
            - mountPath: /btinami/kafka
              name: {{ .Values.kafkaLogVolume.name }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
