apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-standalone.fullname" . }}
  labels:
    {{- include "kafka-standalone.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: kafka-client
      protocol: TCP
      name: kafka-client
  selector:
    {{- include "kafka-standalone.selectorLabels" . | nindent 4 }}
